# Generated by Django 4.2.7 on 2023-11-10 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drawing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('imgfile', models.ImageField(blank=True, null=True, upload_to='')),
                ('uploadedFile', models.FileField(upload_to='result/')),
                ('create_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('create_date', models.DateTimeField()),
                ('drawing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='palette.drawing')),
            ],
        ),
    ]
