# Generated by Django 4.2.7 on 2023-11-10 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palette', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawing',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
