# Generated by Django 4.2.7 on 2023-11-17 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palette', '0004_comment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drawing',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
