# Generated by Django 4.2.7 on 2023-11-19 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palette', '0005_comment_modify_date_drawing_modify_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
