# Generated by Django 4.2.7 on 2023-11-19 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palette', '0006_alter_comment_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
