# Generated by Django 3.2.13 on 2023-11-24 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palette', '0010_auto_20231121_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='uploadedFile',
            field=models.FileField(blank=True, null=True, upload_to='result/'),
        ),
        migrations.AlterField(
            model_name='drawing',
            name='uploadedFile',
            field=models.FileField(blank=True, null=True, upload_to='result/'),
        ),
    ]
