# Generated by Django 3.2.13 on 2023-11-24 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palette', '0011_auto_20231124_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawing',
            name='imgfile',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='drawing',
            name='uploadedFile',
            field=models.FileField(default=1, upload_to='result/'),
            preserve_default=False,
        ),
    ]
